### ISSUE TITLE
Use named parameters

### ISSUE THREAD

**Issue by florian-lefebvre** [EduWireApps/kdecole-api-dart#1]
For example at https://github.com/EduWireApps/kdecole-api-dart/blob/ee5d4aac0fd9c11b9874b7260cd4190323480d05/lib/src/entities/email.dart#L10, it would be better to use named parameters like:
```dart
Email({required this._title, required this._body, required this._sender, required this._receivers, required this._id, required this._messages}); 
```
Also, what is the interest of using private attributes along getters there @Freezman31?

**Comment by Freezman31** [comment]
It's my Java habits x)
I'm going to change this
